#!/usr/bin/env node
// Generate catalog.json from packs/*/. The app reads only `id` + `files[]`
// from each entry; everything else here is for the browse site
// (fella-web/marketplace/). Run this and commit the result CI fails if the
// committed catalog.json doesn't match a fresh build.
//
//   node scripts/build-catalog.mjs [--base <url>] [--check]
//
// --base   URL prefix the pack file URLs are built from. Default is the raw
//          GitHub URL on `main`. Point it at packs.fella.dev when that exists.
// --check  exit non-zero if catalog.json is out of date (don't rewrite it).

import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderMarkdown } from './md.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PACKS_DIR = join(ROOT, 'packs');
const OUT = join(ROOT, 'catalog.json');

const args = process.argv.slice(2);
const check = args.includes('--check');
const baseIx = args.indexOf('--base');
const BASE =
	baseIx >= 0
		? args[baseIx + 1].replace(/\/+$/, '')
		: 'https://raw.githubusercontent.com/Avijit-Kumar-GIT/fella-extensions/main';

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

function git(...a) {
	try {
		return execFileSync('git', a, { cwd: ROOT, encoding: 'utf8' }).trim();
	} catch {
		return '';
	}
}

/** ISO date a path was first added / last touched, from git history. */
const firstAdded = (p) => {
	// Earliest commit that added a file under this path (--reverse, take head).
	const all = git('log', '--diff-filter=A', '--format=%aI', '--reverse', '--', p);
	return all ? all.split('\n')[0] : null;
};
const lastTouched = (p) => git('log', '--format=%aI', '-1', '--', p) || null;

// Keep any install counts a counter service has written into the current file.
let prevInstalls = {};
if (existsSync(OUT)) {
	try {
		for (const p of JSON.parse(readFileSync(OUT, 'utf8')).packs ?? []) {
			if (typeof p.installs === 'number') prevInstalls[p.id] = p.installs;
		}
	} catch {
		/* rebuild from scratch */
	}
}

const problems = [];
const packDirs = existsSync(PACKS_DIR)
	? readdirSync(PACKS_DIR).filter((d) => statSync(join(PACKS_DIR, d)).isDirectory())
	: [];

const packs = [];
for (const id of packDirs.sort()) {
	const dir = join(PACKS_DIR, id);
	const manifestPath = join(dir, 'fella-pack.json');
	if (!existsSync(manifestPath)) {
		problems.push(`${id}: no fella-pack.json`);
		continue;
	}
	let m;
	try {
		m = JSON.parse(readFileSync(manifestPath, 'utf8'));
	} catch (e) {
		problems.push(`${id}: fella-pack.json is not valid JSON (${e.message})`);
		continue;
	}
	if (m.id !== id) problems.push(`${id}: manifest id "${m.id}" != directory name`);
	for (const f of ['README.md', 'LICENSE']) {
		if (!existsSync(join(dir, f))) problems.push(`${id}: missing ${f}`);
	}
	if (!m.payload || !existsSync(join(dir, m.payload))) {
		problems.push(`${id}: payload "${m.payload}" not found`);
		continue;
	}

	const fileNames = ['fella-pack.json', m.payload];
	let sizeBytes = 0;
	const files = fileNames.map((path) => {
		const buf = readFileSync(join(dir, path));
		sizeBytes += buf.length;
		// Every pack lives under packs/<id>/ here, so its URL is --base relative.
		// content is sha256-locked regardless. An externally hosted pack would
		// need SHA-pinned URLs and isn't supported by this script yet.
		return { path, url: `${BASE}/packs/${id}/${path}`, sha256: sha256(buf) };
	});

	const readme = existsSync(join(dir, 'README.md'))
		? renderMarkdown(readFileSync(join(dir, 'README.md'), 'utf8'))
		: '';

	packs.push({
		id,
		kind: m.kind,
		name: m.name,
		version: m.version,
		description: m.description,
		author: m.author || '',
		license: m.license || '',
		homepage: m.homepage || `https://github.com/Avijit-Kumar-GIT/fella-extensions/tree/main/packs/${id}`,
		published: firstAdded(dir),
		updated: lastTouched(dir),
		size_bytes: sizeBytes,
		installs: prevInstalls[id] ?? null,
		readme_html: readme,
		files
	});
}

if (problems.length) {
	console.error('pack problems:\n  ' + problems.join('\n  '));
	process.exit(1);
}

const catalog = {
	schema: 1,
	_comment:
		'Generated by scripts/build-catalog.mjs do not hand-edit. The Fella app reads only id + files[] from each entry; every file is checked against its sha256 on install. Run the script and commit; CI enforces freshness.',
	generated_at: new Date().toISOString().replace(/\.\d+Z$/, 'Z'),
	base: BASE,
	packs
};

const json = JSON.stringify(catalog, null, 2) + '\n';

if (check) {
	// Freshness check = "did the pack contents change without a rebuild?".
	// Compare everything except the timestamps that legitimately drift on a
	// rebuild: generated_at (wall clock) and the git-derived published/updated
	// (a squash/merge commit re-dates the pack directory). Those are metadata
	// for the site, not integrity-bearing sha256 / size / readme_html / files.
	const volatile = (c) => {
		const { generated_at, ...rest } = c;
		rest.packs = (rest.packs ?? []).map(({ published, updated, ...p }) => p);
		return JSON.stringify(rest);
	};
	let current = {};
	try {
		current = JSON.parse(readFileSync(OUT, 'utf8'));
	} catch {
		/* missing or unparseable -> stale */
	}
	if (volatile(current) !== volatile(catalog)) {
		console.error('catalog.json is stale run: node scripts/build-catalog.mjs');
		process.exit(1);
	}
	console.log(`catalog.json is up to date (${packs.length} pack${packs.length === 1 ? '' : 's'}).`);
} else {
	writeFileSync(OUT, json);
	console.log(`wrote catalog.json (${packs.length} pack${packs.length === 1 ? '' : 's'}).`);
}
